kubecostAggregator:
  deployMethod: singlepod
  
kubecostProductConfigs:
  clusterName: aksdevne
#  cloudIntegrationSecret: cloud-integration
  productKey:
    enabled: true
    key: KC-EL80-004P-L11C
    
#federatedETL:
#  federatedCluster: true
  
kubecostModel:
  plugins:
    enabled: false
#  federatedStorageConfigSecret: kubecost-federated-store

kubecostMetrics:
  exporter:
    nodeSelector:
      kubernetes.io/os: linux

nodeSelector:
  kubernetes.io/os: linux

grafana:
  nodeSelector:
    kubernetes.io/os: linux
  
serviceAccount: 
# This example has Kubecost create the service account + annotation. It does not automatically configure the role/ to trust the service account.
# To use a dedicated service account, set create to false, remove the annotation, and specify the name of your dedicated service account. 
  create: true
    
global:
  prometheus:
    enabled: true
    # fqdn: http://prometheus-operated.monitoring:9090
  grafana:
    enabled: true
    
prometheus:
  nodeExporter: # node exporter is disabled by default, enable if needed
    enabled: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
  server:
    global:
      external_labels:
        # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
        cluster_id: aksdevne
    nodeSelector:
      kubernetes.io/os: linux
        
networkCosts:
  # optional, see: https://docs.kubecost.com/install-and-configure/advanced-configuration/network-costs-configuration
  enabled: true
  config:
    services:
      # set the appropriate cloud provider to true
      amazon-web-services: false
      google-cloud-services: false
      azure-cloud-services: true
  nodeSelector:
    kubernetes.io/os: linux

# SAML integration for user management and RBAC, enterprise key required
# Ref: https://github.com/kubecost/docs/blob/master/user-management.md
saml:
  enabled: true
  secretName: "kubecost-azuread"
  # metadataSecretName: "kubecost-azuread-metadata" # One of metadataSecretName or idpMetadataURL must be set. defaults to metadataURL if set
  idpMetadataURL: "https://login.microsoftonline.com/3a4af158-b8a5-4bc8-833c-d973205f2bc2/federationmetadata/2007-06/federationmetadata.xml?appid=dbc032c8-2590-41f5-b0c6-05ed7e8e83c9"
  appRootURL: "https://kubecost.assessor.rm.com" # sample URL
  authTimeout: 1440 # number of minutes the JWT will be valid
  # redirectURL:  # callback URL redirected to after logout
  audienceURI: "https://kubecost.assessor.rm.com" # by convention, the same as the appRootURL, but any string uniquely identifying kubecost to your saml IDP. Optional if you follow the convention
  # nameIDFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" # If your SAML provider requires a specific nameid format
  # isGLUUProvider: false # An additional URL parameter must be appended for GLUU providers
  rbac:
   enabled: true
upgrade:
  toV2: true